admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 192.168.42.1, port_value: 10000 }
    freebind: true
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: service_local }
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_local
    connect_timeout: 30s
    type: STATIC
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 10001
# TODO(htuch): Figure out how to do end-to-end testing with
# outgoing connections and free bind.
#    upstream_bind_config:
#      source_address:
#        address: 192.168.43.1
#      freebind: true
